mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
sa-token:
  active-timeout: -1
  is-concurrent: true
  is-log: true
  is-share: false
  timeout: 2592000
  token-name: satoken
  token-style: uuid
spring:
  application:
    name: saToken
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/satoken?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10s
server:
  port: 10011
